package Model;

public class Edit {
   
    public String message_text;
    /**
     * A default, no-args constructor, as well as correctly formatted getters and setters, are needed for
     * Jackson Objectmapper to work.
     */
    public Edit(){

    }
    /**
     * When posting a new Account, the id can be generated by the database. In that case, a constructor without
     * message_text is needed.
     * @param message_text
     */
    public Edit(String message_text){
        this.message_text = message_text;
    }
    
    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     * @return message_text
     */
    public String getmessage_text() {
        return message_text;
    }
    /**
     * Properly named getters and setters are necessary for Jackson ObjectMapper to work. You may use them as well.
     * @param message_text
     */
    public void setmessage_text(String message_text) {
        this.message_text = message_text;
    }
    /**
     * Overriding the default equals() method adds functionality to tell when two objects are identical, allowing
     * Assert.assertEquals and List.contains to function.
     * @param o the other object.
     * @return true if o is equal to this object.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Edit account = (Edit) o;
        return message_text == account.message_text;
    }
    /**
     * Overriding the default toString() method allows for easy debugging.
     * @return a String representation of this class.
     */
    @Override
    public String toString() {
        return "Edit{" +
                "message_text=" + message_text +
                '}';
    }
}
